### ISSUE TITLE
Visibility of query_next_node, first_from_graph, and last_from_graph

### ISSUE THREAD

**Issue by jpstroop** [samvera-labs/rdf-proxy_list#5]
Should `RDF::ProxyList#query_next_node`, `RDF::ProxyList#first_from_graph`, and `RDF::ProxyList#last_from_graph` be private or protected? 

Assuming that the next logical step is to implement other Array-ish (and Graph-ish?) methods on instances (`pl#[]`, `pl#first`, `pl#last`, `pl#unshift`, `pl#insert`, `pl#delete`, `pl#index`, and  `pl#include?` come to mind), when would/should and API user use these?

**Comment by no-reply** [comment]
`#query_next_node`, at least, provides functionality that isn't available with an instance (finding the next node without knowing the `aggregator`'s URI).  

At least for now, the other two methods are also useful outside of the context of an instance.  They (1) don't require that you convert the entire graph into an in-memory array; and (2) don't require that the graph represent a well constructed and complete list in order to find the elements you are looking for.

It's possible (desirable?) that instances can be changed to deal with the last two points. For now, I'd argue for leaving them public.

**Comment by jpstroop** [comment]
That's fine. Do you agree with the instance methods I listed? (Not that I'll get to them today, just as a point of clarification).

I'd been assuming, e.g., that `pl#first` would simply pass itself to `RDF::ProxyList#first_from_graph` but your comment above suggests that you'd rather see as much delegated (either literally with `def_delegators` or practically, similar to your implementation of `<<`) to `:elements` as possible.

**Comment by no-reply** [comment]
As long as `#initialize` builds the array in full, I think `#first` and `#last` will be better optimized as delegations to `@elements`.  Calling `.first_from_graph` currently requires building the graph from the list, then querying it with `RDF::Query`.  I'm certain we can do better, but as-is delegation seems like the way to go.

**Comment by no-reply** [comment]
Closing this, as there seems to be agreement that no action is required.

**Comment by jpstroop** [comment]
:+1:
